### ISSUE TITLE
Rename to @types/wow-declarations on npm?

### ISSUE THREAD

**Issue by tstirrat** [wartoshika/wow-declarations#2]
I am currently using these types with TypeScriptToLua, they are so so helpful, thanks!

Would you, or have you considered naming `@types/wow-declarations`? It would require no `tsconfig.json` update if this was rooted in `@types/` because the default typeRoots includes anything with `@types/**/*`

**Comment by wartoshika** [comment]
I will look into this. If this is just a renaming, ill do this. But i think a pull request for the @types repository is necessary.

**Comment by wartoshika** [comment]
After looking into this, i decided **not to go** with `@types/wow-declaration` because the process behind the `@types` repository may rejects the pull request since World of Warcraft is no known javascript library.

Since this repository currently gets frequently changes i'll wait before trying to create a pull request for `@types`.

Since Typescript provides a way to include own declaration files (wich are documented in the `readme.md` file of this project) no user should have problems with getting this declaration files to work with their project.
